### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by KFeye** [microgenlab/porefile#10]
Hello!

So, I am slightly obsessed with the idea of this analysis tool, so I apologize if I ask too many questions.  I am trying to run the program (MacOS) and I have been using the barcode kit (96 expansion) and am trying very hard to get to a spot where I have taxa bar plots and diversity analysis. 

I demultiplexed and trimmed in guppy.  I have 96 folders with fastq.gz files (multiple per barcode).  How would I read that data in and do I need to pre-process it any other way (so unzip everything and put it in one fast.gz file??  Also, does it make sense to go to google cloud?  Is there a metadata file I need to create? 

This is truly great work.  Thank you!

**Comment by iferres** [comment]
Hi @KFeye, thanks for your words haha. Very funny the "obsessed" part. We are glad you find it useful.

Idk your experience with nextflow and docker/singularity, but the pipeline should work on your data. Are you having any problem with that?

May be use `--fq */*.fastq.gz` to grab files within sub-folders, that should work.

 If it's already demultiplexed, pass the `--isDemultiplexed` to avoid running Porechop. The pipeline will consider each file as a different barcode and will process them separately. 

There's also an issue with the conda version of Nanoplot, which makes the pipeline fail. Use `--noNanoplot` if that happens.
